name: ysl

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  branch: "MaD"
  username: "flaahokiller"  
  repo: "flasho_Ysl"

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Setup environment
         run: |
           sudo apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex bison cpio
           mkdir ~/bin && PATH=~/bin:$PATH && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
       - name: Downloading script from github repo
         run: |
           wget https://raw.githubusercontent.com/$username/$repo/$branch/build.sh
           bash build.sh
